runtime: go
env: flex
skip_files:
- scripts/
- config/
env_variables:
  ENV: production
  PROJECT_ID: rising-artifact-182801
  KMS_LOCATION_ID: global
  KMS_KEYRING_ID: airbot
  KMS_CRYPTOKEY_ID: secrets
  STORAGE_BUCKET_NAME: storage-rising-artifact-182801
  