#!/usr/bin/env bash

APP_DIR="$HOME/src/github.com/devonboyer/airbot/cmd/airbot"
GCLOUD_ACCOUNT="hello@devonboyer.com"
PROJECT_ID="rising-artifact-182801" # Playground
VERSION=$(git rev-parse --short HEAD)

cd ${APP_DIR} && gcloud app deploy --account=${GCLOUD_ACCOUNT} --project=${PROJECT_ID} --version=${VERSION}
