#!/usr/bin/env bash

APP_DIR="$HOME/src/github.com/devonboyer/airbot/app"
GCLOUD_ACCOUNT="hello@devonboyer.com"
COMMIT=$(git rev-parse HEAD)
PROJECT_ID="rising-artifact-182801" # Playground

if [ $(gcloud config get-value account) != $GCLOUD_ACCOUNT ]; then
  echo "Wrong gcloud account"
  exit 1
fi

cd $APP_DIR && gcloud app deploy --project=$PROJECT_ID --version=$COMMIT
