#!/usr/bin/env bash

PROJECT_DIR="$HOME/src/github.com/devonboyer/airbot"
GCLOUD_ACCOUNT="hello@devonboyer.com"
PLAINTEXT=$(cat $PROJECT_DIR/config/secrets.json | base64)
PROJECT_ID="rising-artifact-182801" # Playground
KEYRING_NAME="secrets"
CRYPTOKEY_NAME="airbot"

if [ $(gcloud config get-value account) != $GCLOUD_ACCOUNT ]; then
  echo "Wrong gcloud account"
  exit 1
fi

# Encrypt with Google Cloud KMS
curl -s -X POST "https://cloudkms.googleapis.com/v1/projects/$PROJECT_ID/locations/global/keyRings/$KEYRING_NAME/cryptoKeys/$CRYPTOKEY_NAME:encrypt" \
  -d "{\"plaintext\":\"$PLAINTEXT\"}" \
  -H "Authorization:Bearer $(gcloud auth application-default print-access-token)" \
  -H "Content-Type:application/json"

# Push encrypted secrets to Google Cloud Storage
# gsutil -m cp *.encrypted gs://${BUCKET_NAME} --p
