#!/usr/bin/env bash

PROJECT_DIR="$HOME/src/github.com/devonboyer/airbot"
GCLOUD_ACCOUNT="hello@devonboyer.com"
PROJECT_ID="rising-artifact-182801" # Playground
KEYRING_NAME="airbot"
ACCESS_TOKEN=$(gcloud auth print-access-token --account=${GCLOUD_ACCOUNT})
BUCKET_NAME="storage-rising-artifact-182801"

encrypt() {
  plaintext=$(cat ${PROJECT_DIR}/config/$1.json| base64)
  encrypted_file="${PROJECT_DIR}/config/$1.encrypted"

  curl -s -X POST "https://cloudkms.googleapis.com/v1/projects/${PROJECT_ID}/locations/global/keyRings/${KEYRING_NAME}/cryptoKeys/$1:encrypt" \
    -d "{\"plaintext\":\"${plaintext}\"}" \
    -H "Authorization:Bearer ${ACCESS_TOKEN}" \
    -H "Content-Type:application/json" \
    | jq .ciphertext -r > ${encrypted_file}
}

decrypt() {
  ciphertext=$(cat ${PROJECT_DIR}/config/$1.encrypted)

  curl -s -X POST "https://cloudkms.googleapis.com/v1/projects/${PROJECT_ID}/locations/global/keyRings/${KEYRING_NAME}/cryptoKeys/$1:decrypt" \
    -d "{\"ciphertext\":\"${ciphertext}\"}" \
    -H "Authorization:Bearer ${ACCESS_TOKEN}" \
    -H "Content-Type:application/json" \
    | jq .plaintext -r | base64 -D > "${PROJECT_DIR}/config/$1.json"
}

push() {
    cd "${PROJECT_DIR}/config" && gsutil cp *.encrypted gs://${BUCKET_NAME}
}

subcommand=$1
case $subcommand in
    *)
        shift
        ${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            exit 1
        fi
        ;;
esac